FishBun/src/main/res/values-ko/strings.xml, FishBun/src/main/res/values/strings.xml
app_name string 리소스가 라이브러리에 남아있어서 앱 이름이 FishBun 으로 출력
=> remove app_name string resource

FishBun/src/main/java/com/sangcomz/fishbun/ui/album/AlbumActivity.java
Replace "ok" and "no" by boolean and clean asynctask
=> Clean use of AsyncTask

FishBun/src/main/java/com/sangcomz/fishbun/ui/picker/PickerActivity.java
Cause:
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=24; index=24
at com.sangcomz.fishbun.ui.picker.PickerActivity.getAllMediaThumbnailsPath(Unknown Source)
at com.sangcomz.fishbun.ui.picker.PickerActivity.getAllMediaThumbnailsPath(Unknown Source)
at com.sangcomz.fishbun.ui.picker.PickerActivity$DisplayImage$1.run(Unknown Source)
at java.lang.Thread.run(Thread.java:841)
=> Fixed ArrayIndexOutOfBoundsException in PickerActivity.

.travis.yml, FishBun/FishBun-FishBun.iml, FishBun/build.gradle, FishBun/src/main/java/com/sangcomz/fishbun/FishBun.java, FishBun/src/main/java/com/sangcomz/fishbun/adapter/AlbumListAdapter.java, FishBun/src/main/java/com/sangcomz/fishbun/adapter/PickerGridAdapter.java, FishBun/src/main/java/com/sangcomz/fishbun/bean/Album.java, FishBun/src/main/java/com/sangcomz/fishbun/define/Define.java, FishBun/src/main/java/com/sangcomz/fishbun/ui/album/AlbumActivity.java, FishBun/src/main/java/com/sangcomz/fishbun/ui/album/AlbumController.java, FishBun/src/main/java/com/sangcomz/fishbun/ui/picker/PickerActivity.java, FishBun/src/main/java/com/sangcomz/fishbun/ui/picker/PickerController.java, FishBunDemo/FishBunDemo.iml, FishBunDemo/build.gradle, FishBunDemo/src/main/java/com/sangcomz/albumsample/CommonApplication.java, FishBunDemo/src/main/java/com/sangcomz/albumsample/MainActivity.java
=> Remove rx and Add new Feature issue#28

FishBun/proguard-rules.pro, FishBunDemo/build.gradle, FishBunDemo/proguard-rules.pro
=> fix(proguard): fix proguard build error (#60)

FishBunDemo/src/main/java/com/sangcomz/fishbundemo/SubFragment.java, FishBunDemo/src/main/res/layout/fragment_sub.xml
- fix FishBunDemo fix sub fragment RecycleryView id
=> fix(SubFragment): fix recyclerview id

FishBun/src/main/java/com/sangcomz/fishbun/FishBun.java, FishBun/src/main/java/com/sangcomz/fishbun/define/Define.java, FishBun/src/main/java/com/sangcomz/fishbun/ui/album/AlbumActivity.java, FishBun/src/main/java/com/sangcomz/fishbun/ui/picker/PickerActivity.java, FishBunDemo/src/main/java/com/sangcomz/fishbundemo/MainActivity.java, FishBunDemo/src/main/res/drawable/ic_arrow_back_black_24dp.xml, FishBunDemo/src/main/res/drawable/ic_check_black_24dp.xml
=> feat(FishBun): set icon, home indicator, menu item (#59)

FishBun/src/main/java/com/sangcomz/fishbun/FishBun.java, FishBun/src/main/java/com/sangcomz/fishbun/define/Define.java, FishBun/src/main/java/com/sangcomz/fishbun/ui/album/AlbumActivity.java, FishBun/src/main/java/com/sangcomz/fishbun/ui/picker/PickerActivity.java, FishBun/src/main/java/com/sangcomz/fishbun/util/UiUtil.java
- add feat (set light status bar)
=> feat(libary): feat light status bar style (#69)

FishBun/src/main/java/com/sangcomz/fishbun/adapter/AlbumListAdapter.java, FishBun/src/main/java/com/sangcomz/fishbun/ui/album/AlbumActivity.java, FishBun/src/main/java/com/sangcomz/fishbun/ui/picker/PickerActivity.java
- show number of image on album
=> feat(AlbumActivity):show number of image on album

FishBun/build.gradle, FishBun/src/main/java/com/sangcomz/fishbun/adapter/PickerGridAdapter.java, FishBun/src/main/java/com/sangcomz/fishbun/ui/album/AlbumActivity.java, FishBun/src/main/java/com/sangcomz/fishbun/ui/picker/PickerActivity.java, FishBun/src/main/java/com/sangcomz/fishbun/ui/picker/PickerController.java, FishBun/src/main/res/layout/thumb_item.xml
- refactoring logic - PickerActivity
- add selection effect
=> Feature/add effect #76

FishBun/src/main/java/com/sangcomz/fishbun/FishBun.java, FishBun/src/main/java/com/sangcomz/fishbun/adapter/PickerGridAdapter.java, FishBun/src/main/java/com/sangcomz/fishbun/define/Define.java, FishBun/src/main/java/com/sangcomz/fishbun/ui/album/AlbumActivity.java, FishBun/src/main/java/com/sangcomz/fishbun/ui/picker/PickerActivity.java, FishBunDemo/src/main/java/com/sangcomz/fishbundemo/WithActivityActivity.java
- fix method name
- add setMinCount()
=> feat(FishBun): fix method name and add min count (#75)

FishBun/src/main/java/com/sangcomz/fishbun/adapter/AlbumListAdapter.java, FishBun/src/main/java/com/sangcomz/fishbun/adapter/PickerGridAdapter.java, FishBun/src/main/java/com/sangcomz/fishbun/ui/picker/PickerActivity.java, FishBun/src/main/java/com/sangcomz/fishbun/util/RadioWithTextButton.java, FishBun/src/main/java/com/sangcomz/fishbun/util/SquareImageView.java, FishBun/src/main/java/com/sangcomz/fishbun/util/SquareTextView.java, FishBun/src/main/java/com/sangcomz/fishbun/util/UiUtil.java, FishBun/src/main/res/layout/album_item.xml, FishBun/src/main/res/layout/thumb_item.xml, FishBunDemo/src/main/java/com/sangcomz/fishbundemo/WithActivityActivity.java
- add RadioWithTextButton
- fix picker design
=> feat(RadioWithTextButton): add widget

FishBun/src/main/java/com/sangcomz/fishbun/ui/album/AlbumController.java
=> fix (AlbumController): fix count zero bug (#96)

FishBun/src/main/AndroidManifest.xml, FishBun/src/main/java/com/sangcomz/fishbun/util/CameraUtil.java, FishBun/src/main/res/xml/provider_paths.xml
=> fix(provider) : fix file provider

FishBun/build.gradle
- fix travis build failed issue
=> fix travis build fail

codecov.yml
=> add codecov.yml

codecov.yml
=> add patch threshold

README.md
Pandaz 앱의 플레이스토어 링크 끊김
-  Pandaz 앱 내용 삭제
=> Pandaz 앱의 플레이스토어 링크 끊김

FishBun/src/main/java/com/sangcomz/fishbun/datasource/PickerIntentDataSourceImpl.kt, FishBun/src/main/res/layout/header_item.xml, FishBunDemo/src/main/AndroidManifest.xml, FishBunDemo/src/main/java/com/sangcomz/fishbundemo/SubFragment.kt, FishBunDemo/src/main/java/com/sangcomz/fishbundemo/WithActivityActivity.kt, README.md, settings.gradle
- Add manifest query to allow camera to launch properly on Android API 30
- Fix some runtime nullability errors with arrayLists
- Update README
- Add ripple to camera button
=> Update to android 11

FishBun/src/main/res/values-zh/strings.xml, FishBunDemo/build.gradle
- No issues fixed.
- As a customer of [multi_image_picker](https://github.com/Sh1d0w/multi_image_picker) which based on FishBun, I want to show message in Chinese instead of English.
=> Support zh rcn

FishBun/build.gradle, FishBun/src/main/java/com/sangcomz/fishbun/ui/album/adapter/AlbumListAdapter.kt, FishBun/src/main/java/com/sangcomz/fishbun/ui/detail/adapter/DetailViewPagerAdapter.kt, FishBunDemo/build.gradle, FishBunDemo/src/main/java/com/sangcomz/fishbundemo/ImageAdapter.kt, FishBunDemo/src/main/java/com/sangcomz/fishbundemo/SubFragment.kt, FishBunDemo/src/main/java/com/sangcomz/fishbundemo/WithActivityActivity.kt, FishBunDemo/src/main/java/com/sangcomz/fishbundemo/WithFragmentActivity.kt, build.gradle, gradle/wrapper/gradle-wrapper.properties
- Kotlin version update (`1.3.50` -> `1.4.10`)
- remove `kotlin-android-extensions`
- AGP update (`4.0.1` -> `4.1.0`)
=> update kotlin version and AGP
